name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Local Docker
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.LOCAL_SERVER_HOST }}
        username: ${{ secrets.LOCAL_SERVER_USER }}
        password: ${{ secrets.LOCAL_SERVER_PASSWORD }} 
        port: 3000
        script: |
          cd /home/usuario/Documentos/GitHub/GitHubs-Actions
          git pull origin main
          docker build -t meu-projeto:latest .
          docker stop meu-projeto || true
          docker rm meu-projeto || true
          docker run -d -p 3000:3000 -p 2222:22 --name my-container my-image
          docker image prune -f  # Limpa imagens antigas
